#!/usr/bin/env php
<?php

$buildtoolsDir = $dir = dirname(__FILE__);
while(strlen($dir) > 2 && !file_exists("$dir/sapphire")) {
	$dir = dirname($dir);
}
if(!file_exists("$dir/sapphire")) {
	echo "ERROR: Can't find a /sapphire directory to work out where the project is.
This script is designed for SilverStripe.\n";
	exit(1);
}

$buildtoolsRelDir = substr($buildtoolsDir, strlen($dir)+1);

passhtru("./newproject " . escapeshellarg($dir) . " " . escapeshellarg($buildtoolsRelDir));